---
title: "Potential_sites_2020"
author: "Lia Domke"
date: "2/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. read in data
2. subset by no otter sites
3. map sites


# 1. Data and libraries
```{r}
noaa <- read.csv("../../APECS Master repository/APECS Master repo/ALL_DATA/noaa_seak_fish_atlas_CLEAN.csv",
                 stringsAsFactors = FALSE, header = TRUE)
```

Libraries
```{r}
library(tidyverse)
library(maps)
library(mapdata)
```
# 2. subset by no otter sites
```{r}
head(noaa)

no.otts <- c(602, 603, 605, 606, 607, 610, 611, 613, 614, 616, 617, 619, 620, 162,165)

noaa.sub <- subset(noaa, SiteID %in% no.otts)

noaa.sub <- noaa.sub %>%
  dplyr::select(-c(X, Season, Mon, SeasonNoYear))
```

# 3. map sites

working on this... the inset map portion does not work
try using patchwork DUH to put the inset map with the map!!! 
```{r}
library(grid)

ak <- map_data("world2Hires", "USA:alaska")
ak$long <- ak$long - 360

inset_map <- ggplotGrob(ggplot() +
  geom_polygon(ak, mapping = aes(long, lat, group = group)) +
  coord_fixed(ratio = 1.3) +
  xlab("") +
  ylab("") +
  annotate(geom = "rect", ymax = 56, ymin = 54, xmax = -135, xmin = -130, fill = NA, colour = "red") +
  theme_bw())
inset_map

base_map <- ggplot(noaa.sub) +
  geom_point(mapping = aes(Long1, Lat1, colour = Habitat)) +
  geom_polygon(mapping = aes(long, lat, group = group), data = ak, fill = "#666666") +
  coord_map(xlim = c(-134, -130), ylim = c(54.5, 57)) +
  scale_color_manual(values = c("#339900", "#D16103")) +
  theme_bw()

base_map 

map <- ggdraw()  +
  draw_plot(base_map) +
  draw_plot(inset_map, x = 0.5, y = 0.7, width = .25, height = .3)
map


require(patchwork)
inset_map / base_map

```

